### PR TITLE
Add skeleton to README and create SYLLABUS

### PR DESCRIPTION
**Pull request by matthewfeickert**

### CODE REVIEW

**Comment by matthewfeickert** [comment]
These commits can be merged onto `master` unless there are extra edits to make right away.

Also, sorry @stephensekula. I didn't bother to do `git branch -a` to see that you already had a `dev` branch before starting my own. Once these changes are merged in we should delete my `dev` branch and then I can just check out yours from the remote.

**Comment by stephensekula** [comment]
Well, I wasn't paying close attention, either. You moved fast! Do I now delete the dev branch and then push my own the repo? There's really nothing of great note lurking in my local dev branch.

**Comment by matthewfeickert** [comment]
@stephensekula Yeah that sounds good. Once you've done that, then I can just do a `git pull` and then I'll be able to just checkout the `dev` branch that you've pushed with `git checkout origin/dev -b dev` and then we can both work on it. 

Anytime we want a new feature, just create an issue, assign a person to the issue, and that person can create a new branch which will ultimately get merged in at the end. :thumbsup:

**Comment by stephensekula** [comment]
Very good. It will take me a bit to get used to this workflow. I've mostly done solo development in github. Should catch up fast, though...

**Pull request merged**
